// SPDX-License-Identifier: Apache-2.0
export interface DesignTemplate {
  id: string;
  name: string;
  category: string;
  width: number;
  height: number;
  icon: string;
  description: string;
}

export const DESIGN_TEMPLATES: DesignTemplate[] = [
  // ─────────────────────────────────────────────────────────
  // SOCIAL MEDIA (30 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'instagram-post',
    name: 'Instagram Post',
    category: 'Social Media',
    width: 1080,
    height: 1080,
    icon: '📱',
    description: 'Square post for Instagram feed',
  },
  {
    id: 'instagram-story',
    name: 'Instagram Story',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    icon: '📱',
    description: 'Vertical story format',
  },
  {
    id: 'instagram-reel-cover',
    name: 'Instagram Reel Cover',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    icon: '🎬',
    description: 'Cover image for Instagram Reels',
  },
  {
    id: 'instagram-carousel',
    name: 'Instagram Carousel',
    category: 'Social Media',
    width: 1080,
    height: 1350,
    icon: '📱',
    description: 'Portrait carousel slide (4:5)',
  },
  {
    id: 'instagram-highlight-cover',
    name: 'Instagram Highlight Cover',
    category: 'Social Media',
    width: 1080,
    height: 1080,
    icon: '⭕',
    description: 'Story highlight cover icon',
  },
  {
    id: 'instagram-ad',
    name: 'Instagram Ad',
    category: 'Social Media',
    width: 1080,
    height: 1080,
    icon: '📢',
    description: 'Sponsored post format',
  },
  {
    id: 'facebook-post',
    name: 'Facebook Post',
    category: 'Social Media',
    width: 1200,
    height: 630,
    icon: '👤',
    description: 'Standard Facebook shared image',
  },
  {
    id: 'facebook-cover',
    name: 'Facebook Cover',
    category: 'Social Media',
    width: 820,
    height: 312,
    icon: '👤',
    description: 'Facebook page cover photo',
  },
  {
    id: 'facebook-event-cover',
    name: 'Facebook Event Cover',
    category: 'Social Media',
    width: 1920,
    height: 1005,
    icon: '🎉',
    description: 'Event cover image',
  },
  {
    id: 'facebook-story',
    name: 'Facebook Story',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    icon: '👤',
    description: 'Facebook Stories format',
  },
  {
    id: 'facebook-ad',
    name: 'Facebook Ad',
    category: 'Social Media',
    width: 1200,
    height: 628,
    icon: '📢',
    description: 'Facebook feed ad image',
  },
  {
    id: 'facebook-group-cover',
    name: 'Facebook Group Cover',
    category: 'Social Media',
    width: 1640,
    height: 856,
    icon: '👥',
    description: 'Cover for Facebook Groups',
  },
  {
    id: 'twitter-post',
    name: 'X / Twitter Post',
    category: 'Social Media',
    width: 1600,
    height: 900,
    icon: '🐦',
    description: 'In-stream photo for X',
  },
  {
    id: 'twitter-header',
    name: 'X / Twitter Header',
    category: 'Social Media',
    width: 1500,
    height: 500,
    icon: '🐦',
    description: 'Profile header image',
  },
  {
    id: 'twitter-ad',
    name: 'X / Twitter Ad',
    category: 'Social Media',
    width: 800,
    height: 418,
    icon: '📢',
    description: 'Promoted tweet image',
  },
  {
    id: 'linkedin-post',
    name: 'LinkedIn Post',
    category: 'Social Media',
    width: 1200,
    height: 627,
    icon: '💼',
    description: 'LinkedIn feed image',
  },
  {
    id: 'linkedin-cover',
    name: 'LinkedIn Cover',
    category: 'Social Media',
    width: 1584,
    height: 396,
    icon: '💼',
    description: 'LinkedIn profile background',
  },
  {
    id: 'linkedin-banner',
    name: 'LinkedIn Company Banner',
    category: 'Social Media',
    width: 1128,
    height: 191,
    icon: '💼',
    description: 'Company page banner',
  },
  {
    id: 'linkedin-story',
    name: 'LinkedIn Story',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    icon: '💼',
    description: 'LinkedIn Stories format',
  },
  {
    id: 'pinterest-pin',
    name: 'Pinterest Pin',
    category: 'Social Media',
    width: 1000,
    height: 1500,
    icon: '📌',
    description: 'Standard pin (2:3 ratio)',
  },
  {
    id: 'pinterest-long-pin',
    name: 'Pinterest Long Pin',
    category: 'Social Media',
    width: 1000,
    height: 2100,
    icon: '📌',
    description: 'Long-form infographic pin',
  },
  {
    id: 'pinterest-ad',
    name: 'Pinterest Ad',
    category: 'Social Media',
    width: 1000,
    height: 1500,
    icon: '📢',
    description: 'Promoted Pinterest pin',
  },
  {
    id: 'tiktok-video',
    name: 'TikTok Video',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    icon: '🎵',
    description: 'TikTok video / story format',
  },
  {
    id: 'snapchat-geofilter',
    name: 'Snapchat Geofilter',
    category: 'Social Media',
    width: 1080,
    height: 2340,
    icon: '👻',
    description: 'Custom Snapchat filter overlay',
  },
  {
    id: 'youtube-channel-art',
    name: 'YouTube Channel Art',
    category: 'Social Media',
    width: 2560,
    height: 1440,
    icon: '🎬',
    description: 'YouTube banner image',
  },
  {
    id: 'whatsapp-status',
    name: 'WhatsApp Status',
    category: 'Social Media',
    width: 1080,
    height: 1920,
    icon: '💬',
    description: 'WhatsApp status image',
  },
  {
    id: 'discord-server-icon',
    name: 'Discord Server Icon',
    category: 'Social Media',
    width: 512,
    height: 512,
    icon: '🎮',
    description: 'Server icon for Discord',
  },
  {
    id: 'discord-banner',
    name: 'Discord Server Banner',
    category: 'Social Media',
    width: 960,
    height: 540,
    icon: '🎮',
    description: 'Server banner for Discord Nitro',
  },
  {
    id: 'twitch-banner',
    name: 'Twitch Banner',
    category: 'Social Media',
    width: 1200,
    height: 480,
    icon: '🟣',
    description: 'Twitch profile banner',
  },
  {
    id: 'twitch-overlay',
    name: 'Twitch Overlay',
    category: 'Social Media',
    width: 1920,
    height: 1080,
    icon: '🟣',
    description: 'Stream overlay frame',
  },

  // ─────────────────────────────────────────────────────────
  // VIDEO (15 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail',
    category: 'Video',
    width: 1280,
    height: 720,
    icon: '🎬',
    description: 'Video thumbnail for YouTube',
  },
  {
    id: 'youtube-end-screen',
    name: 'YouTube End Screen',
    category: 'Video',
    width: 1920,
    height: 1080,
    icon: '🎬',
    description: 'End screen with subscribe/video links',
  },
  {
    id: 'youtube-intro',
    name: 'YouTube Intro Slide',
    category: 'Video',
    width: 1920,
    height: 1080,
    icon: '🎬',
    description: 'Title card for YouTube intros',
  },
  {
    id: 'video-16-9',
    name: 'Video 16:9',
    category: 'Video',
    width: 1920,
    height: 1080,
    icon: '🎥',
    description: 'Standard widescreen video frame',
  },
  {
    id: 'video-4-3',
    name: 'Video 4:3',
    category: 'Video',
    width: 1440,
    height: 1080,
    icon: '🎥',
    description: 'Classic 4:3 video format',
  },
  {
    id: 'video-1-1',
    name: 'Video Square',
    category: 'Video',
    width: 1080,
    height: 1080,
    icon: '🎥',
    description: 'Square video for social platforms',
  },
  {
    id: 'video-9-16',
    name: 'Video Vertical',
    category: 'Video',
    width: 1080,
    height: 1920,
    icon: '📱',
    description: 'Vertical video / Reels / Shorts',
  },
  {
    id: 'podcast-cover',
    name: 'Podcast Cover Art',
    category: 'Video',
    width: 3000,
    height: 3000,
    icon: '🎙️',
    description: 'Podcast cover (Apple Podcasts spec)',
  },
  {
    id: 'podcast-audiogram',
    name: 'Podcast Audiogram',
    category: 'Video',
    width: 1080,
    height: 1080,
    icon: '🎙️',
    description: 'Audio waveform social clip',
  },
  {
    id: 'video-lower-third',
    name: 'Lower Third',
    category: 'Video',
    width: 1920,
    height: 200,
    icon: '📺',
    description: 'Name/title bar overlay for video',
  },
  {
    id: 'video-4k',
    name: 'Video 4K UHD',
    category: 'Video',
    width: 3840,
    height: 2160,
    icon: '🎥',
    description: 'Ultra HD 4K video frame',
  },
  {
    id: 'twitch-panel',
    name: 'Twitch Panel',
    category: 'Video',
    width: 320,
    height: 100,
    icon: '🟣',
    description: 'Info panel for Twitch channel',
  },
  {
    id: 'twitch-screen',
    name: 'Twitch Starting/BRB Screen',
    category: 'Video',
    width: 1920,
    height: 1080,
    icon: '🟣',
    description: 'Holding screen for streams',
  },
  {
    id: 'animated-sticker',
    name: 'Animated Sticker Frame',
    category: 'Video',
    width: 512,
    height: 512,
    icon: '✨',
    description: 'Static frame for animated stickers',
  },
  {
    id: 'zoom-virtual-bg',
    name: 'Zoom Virtual Background',
    category: 'Video',
    width: 1920,
    height: 1080,
    icon: '💻',
    description: 'Virtual meeting background',
  },

  // ─────────────────────────────────────────────────────────
  // PRINT (20 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'a4-portrait',
    name: 'A4 Portrait',
    category: 'Print',
    width: 2480,
    height: 3508,
    icon: '📄',
    description: '210mm × 297mm at 300 DPI',
  },
  {
    id: 'a4-landscape',
    name: 'A4 Landscape',
    category: 'Print',
    width: 3508,
    height: 2480,
    icon: '📄',
    description: '297mm × 210mm at 300 DPI',
  },
  {
    id: 'us-letter',
    name: 'US Letter',
    category: 'Print',
    width: 2550,
    height: 3300,
    icon: '📄',
    description: '8.5" × 11" at 300 DPI',
  },
  {
    id: 'us-letter-landscape',
    name: 'US Letter Landscape',
    category: 'Print',
    width: 3300,
    height: 2550,
    icon: '📄',
    description: '11" × 8.5" at 300 DPI',
  },
  {
    id: 'us-legal',
    name: 'US Legal',
    category: 'Print',
    width: 2550,
    height: 4200,
    icon: '📄',
    description: '8.5" × 14" at 300 DPI',
  },
  {
    id: 'a5-portrait',
    name: 'A5 Portrait',
    category: 'Print',
    width: 1748,
    height: 2480,
    icon: '📄',
    description: '148mm × 210mm at 300 DPI',
  },
  {
    id: 'a3-portrait',
    name: 'A3 Portrait',
    category: 'Print',
    width: 3508,
    height: 4961,
    icon: '📄',
    description: '297mm × 420mm at 300 DPI',
  },
  {
    id: 'tabloid',
    name: 'Tabloid (11×17)',
    category: 'Print',
    width: 3300,
    height: 5100,
    icon: '📄',
    description: '11" × 17" at 300 DPI',
  },
  {
    id: 'business-card',
    name: 'Business Card',
    category: 'Print',
    width: 1050,
    height: 600,
    icon: '💳',
    description: '3.5" × 2" at 300 DPI',
  },
  {
    id: 'business-card-eu',
    name: 'Business Card (EU)',
    category: 'Print',
    width: 1028,
    height: 638,
    icon: '💳',
    description: '85mm × 55mm at 300 DPI',
  },
  {
    id: 'postcard-4x6',
    name: 'Postcard 4×6',
    category: 'Print',
    width: 1800,
    height: 1200,
    icon: '✉️',
    description: '6" × 4" at 300 DPI',
  },
  {
    id: 'postcard-5x7',
    name: 'Postcard 5×7',
    category: 'Print',
    width: 2100,
    height: 1500,
    icon: '✉️',
    description: '7" × 5" at 300 DPI',
  },
  {
    id: 'envelope-dl',
    name: 'DL Envelope',
    category: 'Print',
    width: 2598,
    height: 1299,
    icon: '✉️',
    description: '220mm × 110mm at 300 DPI',
  },
  {
    id: 'label-2x4',
    name: 'Shipping Label',
    category: 'Print',
    width: 1200,
    height: 600,
    icon: '🏷️',
    description: '4" × 2" at 300 DPI',
  },
  {
    id: 'sticker-circle',
    name: 'Circle Sticker',
    category: 'Print',
    width: 900,
    height: 900,
    icon: '⭕',
    description: '3" diameter circle at 300 DPI',
  },
  {
    id: 'sticker-square',
    name: 'Square Sticker',
    category: 'Print',
    width: 900,
    height: 900,
    icon: '🟦',
    description: '3" × 3" at 300 DPI',
  },
  {
    id: 'bookmark',
    name: 'Bookmark',
    category: 'Print',
    width: 600,
    height: 1800,
    icon: '🔖',
    description: '2" × 6" at 300 DPI',
  },
  {
    id: 'door-hanger',
    name: 'Door Hanger',
    category: 'Print',
    width: 1050,
    height: 2700,
    icon: '🚪',
    description: '3.5" × 9" at 300 DPI',
  },
  {
    id: 'cd-cover',
    name: 'CD/DVD Cover',
    category: 'Print',
    width: 1417,
    height: 1417,
    icon: '💿',
    description: '4.72" square at 300 DPI',
  },
  {
    id: 'photo-4x6',
    name: 'Photo Print 4×6',
    category: 'Print',
    width: 1800,
    height: 1200,
    icon: '📷',
    description: 'Standard 4×6 photo at 300 DPI',
  },

  // ─────────────────────────────────────────────────────────
  // MARKETING (20 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'presentation-16-9',
    name: 'Presentation 16:9',
    category: 'Marketing',
    width: 1920,
    height: 1080,
    icon: '📊',
    description: 'Widescreen presentation slide',
  },
  {
    id: 'presentation-4-3',
    name: 'Presentation 4:3',
    category: 'Marketing',
    width: 1024,
    height: 768,
    icon: '📊',
    description: 'Classic presentation slide',
  },
  {
    id: 'email-header',
    name: 'Email Header',
    category: 'Marketing',
    width: 600,
    height: 200,
    icon: '✉️',
    description: 'Email marketing banner',
  },
  {
    id: 'email-newsletter',
    name: 'Email Newsletter',
    category: 'Marketing',
    width: 600,
    height: 1200,
    icon: '✉️',
    description: 'Full email newsletter layout',
  },
  {
    id: 'web-banner',
    name: 'Web Banner',
    category: 'Marketing',
    width: 1920,
    height: 600,
    icon: '🌐',
    description: 'Hero section banner',
  },
  {
    id: 'web-banner-leaderboard',
    name: 'Leaderboard Banner',
    category: 'Marketing',
    width: 728,
    height: 90,
    icon: '🌐',
    description: 'Standard IAB leaderboard ad',
  },
  {
    id: 'web-banner-skyscraper',
    name: 'Wide Skyscraper',
    category: 'Marketing',
    width: 160,
    height: 600,
    icon: '🌐',
    description: 'Sidebar skyscraper ad',
  },
  {
    id: 'web-banner-rectangle',
    name: 'Medium Rectangle Ad',
    category: 'Marketing',
    width: 300,
    height: 250,
    icon: '🌐',
    description: 'Standard IAB medium rectangle',
  },
  {
    id: 'web-banner-billboard',
    name: 'Billboard Ad',
    category: 'Marketing',
    width: 970,
    height: 250,
    icon: '🌐',
    description: 'Large billboard web ad',
  },
  {
    id: 'google-display-ad',
    name: 'Google Display Ad',
    category: 'Marketing',
    width: 300,
    height: 250,
    icon: '📢',
    description: 'Google Ads display banner',
  },
  {
    id: 'google-display-large',
    name: 'Google Large Rectangle',
    category: 'Marketing',
    width: 336,
    height: 280,
    icon: '📢',
    description: 'Google Ads large rectangle',
  },
  {
    id: 'coupon',
    name: 'Coupon / Voucher',
    category: 'Marketing',
    width: 1800,
    height: 750,
    icon: '🎫',
    description: '6" × 2.5" coupon at 300 DPI',
  },
  {
    id: 'gift-certificate',
    name: 'Gift Certificate',
    category: 'Marketing',
    width: 2400,
    height: 1200,
    icon: '🎁',
    description: '8" × 4" gift card at 300 DPI',
  },
  {
    id: 'loyalty-card',
    name: 'Loyalty Card',
    category: 'Marketing',
    width: 1050,
    height: 600,
    icon: '⭐',
    description: 'Punch card / loyalty card',
  },
  {
    id: 'pull-up-banner',
    name: 'Pull-Up Banner',
    category: 'Marketing',
    width: 2400,
    height: 6000,
    icon: '🪧',
    description: 'Retractable banner stand (2×5 ft)',
  },
  {
    id: 'yard-sign',
    name: 'Yard Sign',
    category: 'Marketing',
    width: 3600,
    height: 2400,
    icon: '🪧',
    description: '24" × 16" corrugated sign',
  },
  {
    id: 'vehicle-wrap-side',
    name: 'Vehicle Wrap (Side)',
    category: 'Marketing',
    width: 4800,
    height: 1800,
    icon: '🚗',
    description: 'Side panel vehicle wrap',
  },
  {
    id: 'trade-show-backdrop',
    name: 'Trade Show Backdrop',
    category: 'Marketing',
    width: 7200,
    height: 3600,
    icon: '🏢',
    description: '10ft × 5ft event backdrop',
  },
  {
    id: 'marketing-brochure-tri',
    name: 'Tri-fold Brochure',
    category: 'Marketing',
    width: 3300,
    height: 2550,
    icon: '📰',
    description: '11" × 8.5" tri-fold',
  },
  {
    id: 'marketing-brochure-bi',
    name: 'Bi-fold Brochure',
    category: 'Marketing',
    width: 2550,
    height: 3300,
    icon: '📰',
    description: '8.5" × 11" bi-fold',
  },

  // ─────────────────────────────────────────────────────────
  // BRANDING (12 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'logo-square',
    name: 'Logo (Square)',
    category: 'Branding',
    width: 500,
    height: 500,
    icon: '🎨',
    description: 'Square logo or icon',
  },
  {
    id: 'logo-horizontal',
    name: 'Logo (Horizontal)',
    category: 'Branding',
    width: 1000,
    height: 300,
    icon: '🎨',
    description: 'Horizontal logo lockup',
  },
  {
    id: 'logo-vertical',
    name: 'Logo (Vertical)',
    category: 'Branding',
    width: 500,
    height: 800,
    icon: '🎨',
    description: 'Vertical / stacked logo',
  },
  {
    id: 'favicon',
    name: 'Favicon',
    category: 'Branding',
    width: 512,
    height: 512,
    icon: '🌐',
    description: 'Browser tab favicon (512×512)',
  },
  {
    id: 'app-icon-ios',
    name: 'App Icon (iOS)',
    category: 'Branding',
    width: 1024,
    height: 1024,
    icon: '📱',
    description: 'iPhone/iPad app icon',
  },
  {
    id: 'app-icon-android',
    name: 'App Icon (Android)',
    category: 'Branding',
    width: 512,
    height: 512,
    icon: '🤖',
    description: 'Google Play app icon',
  },
  {
    id: 'watermark',
    name: 'Watermark',
    category: 'Branding',
    width: 600,
    height: 200,
    icon: '💧',
    description: 'Semi-transparent photo watermark',
  },
  {
    id: 'letterhead',
    name: 'Letterhead',
    category: 'Branding',
    width: 2550,
    height: 3300,
    icon: '📃',
    description: 'Professional letterhead (US Letter)',
  },
  {
    id: 'brand-guidelines',
    name: 'Brand Guideline Page',
    category: 'Branding',
    width: 1920,
    height: 1080,
    icon: '📋',
    description: 'Brand standards document page',
  },
  {
    id: 'email-signature',
    name: 'Email Signature Banner',
    category: 'Branding',
    width: 600,
    height: 100,
    icon: '✉️',
    description: 'HTML email signature graphic',
  },
  {
    id: 'social-profile-pic',
    name: 'Profile Picture',
    category: 'Branding',
    width: 800,
    height: 800,
    icon: '👤',
    description: 'Universal social profile pic',
  },
  {
    id: 'og-image',
    name: 'Open Graph Image',
    category: 'Branding',
    width: 1200,
    height: 630,
    icon: '🌐',
    description: 'Link preview image (og:image)',
  },

  // ─────────────────────────────────────────────────────────
  // PRESENTATIONS (12 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'slide-16-9',
    name: 'Slide 16:9',
    category: 'Presentations',
    width: 1920,
    height: 1080,
    icon: '📊',
    description: 'Widescreen slide',
  },
  {
    id: 'slide-4-3',
    name: 'Slide 4:3',
    category: 'Presentations',
    width: 1024,
    height: 768,
    icon: '📊',
    description: 'Classic aspect ratio slide',
  },
  {
    id: 'slide-a4',
    name: 'Slide A4',
    category: 'Presentations',
    width: 1123,
    height: 794,
    icon: '📊',
    description: 'A4-proportioned slide',
  },
  {
    id: 'pitch-deck-slide',
    name: 'Pitch Deck Slide',
    category: 'Presentations',
    width: 1920,
    height: 1080,
    icon: '💡',
    description: 'Investor pitch deck page',
  },
  {
    id: 'webinar-slide',
    name: 'Webinar Slide',
    category: 'Presentations',
    width: 1920,
    height: 1080,
    icon: '🎓',
    description: 'Online workshop slide',
  },
  {
    id: 'course-slide',
    name: 'Course Slide',
    category: 'Presentations',
    width: 1920,
    height: 1080,
    icon: '🎓',
    description: 'E-learning / course material',
  },
  {
    id: 'proposal-page',
    name: 'Proposal Page',
    category: 'Presentations',
    width: 1920,
    height: 1080,
    icon: '📝',
    description: 'Client proposal slide',
  },
  {
    id: 'meeting-agenda',
    name: 'Meeting Agenda',
    category: 'Presentations',
    width: 1920,
    height: 1080,
    icon: '📋',
    description: 'Meeting agenda template',
  },
  {
    id: 'quarterly-review',
    name: 'Quarterly Review',
    category: 'Presentations',
    width: 1920,
    height: 1080,
    icon: '📈',
    description: 'Business review slide',
  },
  {
    id: 'social-slide-square',
    name: 'Social Slide (Square)',
    category: 'Presentations',
    width: 1080,
    height: 1080,
    icon: '📊',
    description: 'Square carousel presentation',
  },
  {
    id: 'mobile-slide',
    name: 'Mobile Slide',
    category: 'Presentations',
    width: 1080,
    height: 1920,
    icon: '📱',
    description: 'Vertical mobile presentation',
  },
  {
    id: 'keynote-slide',
    name: 'Keynote / Apple Slide',
    category: 'Presentations',
    width: 2048,
    height: 1536,
    icon: '🍎',
    description: 'Retina presentation slide',
  },

  // ─────────────────────────────────────────────────────────
  // FLYERS & POSTERS (18 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'flyer-a5',
    name: 'Flyer (A5)',
    category: 'Flyers & Posters',
    width: 1748,
    height: 2480,
    icon: '📄',
    description: 'A5 flyer at 300 DPI',
  },
  {
    id: 'flyer-a4',
    name: 'Flyer (A4)',
    category: 'Flyers & Posters',
    width: 2480,
    height: 3508,
    icon: '📄',
    description: 'A4 flyer at 300 DPI',
  },
  {
    id: 'flyer-half-letter',
    name: 'Flyer (Half Letter)',
    category: 'Flyers & Posters',
    width: 1650,
    height: 2550,
    icon: '📄',
    description: '5.5" × 8.5" at 300 DPI',
  },
  {
    id: 'flyer-dl',
    name: 'DL Flyer / Rack Card',
    category: 'Flyers & Posters',
    width: 1240,
    height: 2598,
    icon: '📄',
    description: '99mm × 210mm at 300 DPI',
  },
  {
    id: 'poster-11x17',
    name: 'Poster (11×17)',
    category: 'Flyers & Posters',
    width: 3300,
    height: 5100,
    icon: '🖼️',
    description: 'Tabloid poster at 300 DPI',
  },
  {
    id: 'poster-18x24',
    name: 'Poster (18×24)',
    category: 'Flyers & Posters',
    width: 5400,
    height: 7200,
    icon: '🖼️',
    description: 'Large poster at 300 DPI',
  },
  {
    id: 'poster-24x36',
    name: 'Poster (24×36)',
    category: 'Flyers & Posters',
    width: 7200,
    height: 10800,
    icon: '🖼️',
    description: 'Movie poster size at 300 DPI',
  },
  {
    id: 'poster-a2',
    name: 'Poster (A2)',
    category: 'Flyers & Posters',
    width: 4961,
    height: 7016,
    icon: '🖼️',
    description: '420mm × 594mm at 300 DPI',
  },
  {
    id: 'event-flyer',
    name: 'Event Flyer',
    category: 'Flyers & Posters',
    width: 2550,
    height: 3300,
    icon: '🎉',
    description: 'Concert / event flyer',
  },
  {
    id: 'party-invitation-flyer',
    name: 'Party Invitation',
    category: 'Flyers & Posters',
    width: 1500,
    height: 2100,
    icon: '🎈',
    description: '5" × 7" party invite',
  },
  {
    id: 'sale-flyer',
    name: 'Sale / Promo Flyer',
    category: 'Flyers & Posters',
    width: 2550,
    height: 3300,
    icon: '🏷️',
    description: 'Retail sale flyer',
  },
  {
    id: 'restaurant-flyer',
    name: 'Restaurant Flyer',
    category: 'Flyers & Posters',
    width: 2550,
    height: 3300,
    icon: '🍽️',
    description: 'Restaurant promo flyer',
  },
  {
    id: 'real-estate-flyer',
    name: 'Real Estate Flyer',
    category: 'Flyers & Posters',
    width: 2550,
    height: 3300,
    icon: '🏠',
    description: 'Property listing flyer',
  },
  {
    id: 'music-poster',
    name: 'Music / Gig Poster',
    category: 'Flyers & Posters',
    width: 3300,
    height: 5100,
    icon: '🎵',
    description: 'Concert / gig poster',
  },
  {
    id: 'movie-poster',
    name: 'Movie Poster',
    category: 'Flyers & Posters',
    width: 4050,
    height: 6000,
    icon: '🎬',
    description: '27" × 40" at 150 DPI',
  },
  {
    id: 'motivational-poster',
    name: 'Motivational Poster',
    category: 'Flyers & Posters',
    width: 2400,
    height: 3600,
    icon: '💪',
    description: '8" × 12" inspirational poster',
  },
  {
    id: 'classroom-poster',
    name: 'Classroom Poster',
    category: 'Flyers & Posters',
    width: 2550,
    height: 3300,
    icon: '📚',
    description: 'Educational classroom poster',
  },
  {
    id: 'infographic-poster',
    name: 'Infographic Poster',
    category: 'Flyers & Posters',
    width: 2400,
    height: 7200,
    icon: '📊',
    description: 'Tall infographic / data poster',
  },

  // ─────────────────────────────────────────────────────────
  // CARDS & INVITATIONS (18 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'greeting-card-5x7',
    name: 'Greeting Card (5×7)',
    category: 'Cards & Invitations',
    width: 2100,
    height: 1500,
    icon: '💌',
    description: 'Standard greeting card',
  },
  {
    id: 'greeting-card-4x6',
    name: 'Greeting Card (4×6)',
    category: 'Cards & Invitations',
    width: 1800,
    height: 1200,
    icon: '💌',
    description: '4×6 photo card',
  },
  {
    id: 'wedding-invitation',
    name: 'Wedding Invitation',
    category: 'Cards & Invitations',
    width: 1500,
    height: 2100,
    icon: '💒',
    description: '5" × 7" wedding invite',
  },
  {
    id: 'wedding-save-the-date',
    name: 'Save the Date',
    category: 'Cards & Invitations',
    width: 1800,
    height: 1200,
    icon: '💍',
    description: '6" × 4" save the date card',
  },
  {
    id: 'wedding-rsvp',
    name: 'RSVP Card',
    category: 'Cards & Invitations',
    width: 1050,
    height: 1500,
    icon: '💌',
    description: '3.5" × 5" response card',
  },
  {
    id: 'birthday-card',
    name: 'Birthday Card',
    category: 'Cards & Invitations',
    width: 2100,
    height: 1500,
    icon: '🎂',
    description: 'Birthday greeting card',
  },
  {
    id: 'birthday-invitation',
    name: 'Birthday Invitation',
    category: 'Cards & Invitations',
    width: 1500,
    height: 2100,
    icon: '🎈',
    description: 'Birthday party invite',
  },
  {
    id: 'baby-shower',
    name: 'Baby Shower Invite',
    category: 'Cards & Invitations',
    width: 1500,
    height: 2100,
    icon: '👶',
    description: 'Baby shower invitation',
  },
  {
    id: 'graduation-invitation',
    name: 'Graduation Invite',
    category: 'Cards & Invitations',
    width: 1500,
    height: 2100,
    icon: '🎓',
    description: 'Graduation ceremony invite',
  },
  {
    id: 'holiday-card',
    name: 'Holiday / Christmas Card',
    category: 'Cards & Invitations',
    width: 2100,
    height: 1500,
    icon: '🎄',
    description: 'Holiday greeting card',
  },
  {
    id: 'thank-you-card',
    name: 'Thank You Card',
    category: 'Cards & Invitations',
    width: 2100,
    height: 1500,
    icon: '🙏',
    description: '5" × 7" thank you note',
  },
  {
    id: 'sympathy-card',
    name: 'Sympathy Card',
    category: 'Cards & Invitations',
    width: 2100,
    height: 1500,
    icon: '🕊️',
    description: 'Condolence / sympathy card',
  },
  {
    id: 'placecard',
    name: 'Place Card / Tent Card',
    category: 'Cards & Invitations',
    width: 1050,
    height: 600,
    icon: '🪧',
    description: 'Table place card',
  },
  {
    id: 'recipe-card',
    name: 'Recipe Card',
    category: 'Cards & Invitations',
    width: 1200,
    height: 1800,
    icon: '🍳',
    description: '4" × 6" recipe card',
  },
  {
    id: 'flash-card',
    name: 'Flash Card',
    category: 'Cards & Invitations',
    width: 1050,
    height: 750,
    icon: '📇',
    description: '3.5" × 2.5" learning card',
  },
  {
    id: 'notecard',
    name: 'Notecard / Memo',
    category: 'Cards & Invitations',
    width: 1200,
    height: 900,
    icon: '📝',
    description: '4" × 3" notecard',
  },
  {
    id: 'event-ticket',
    name: 'Event Ticket',
    category: 'Cards & Invitations',
    width: 1800,
    height: 600,
    icon: '🎫',
    description: '6" × 2" event ticket',
  },
  {
    id: 'name-badge',
    name: 'Name Badge',
    category: 'Cards & Invitations',
    width: 1200,
    height: 900,
    icon: '📛',
    description: 'Conference name badge',
  },

  // ─────────────────────────────────────────────────────────
  // MENUS (10 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'menu-a4',
    name: 'Menu (A4)',
    category: 'Menus',
    width: 2480,
    height: 3508,
    icon: '🍽️',
    description: 'Full-page restaurant menu',
  },
  {
    id: 'menu-half-page',
    name: 'Menu (Half Page)',
    category: 'Menus',
    width: 2550,
    height: 1650,
    icon: '🍽️',
    description: 'Half-page menu insert',
  },
  {
    id: 'menu-trifold',
    name: 'Tri-fold Menu',
    category: 'Menus',
    width: 3300,
    height: 2550,
    icon: '🍽️',
    description: 'Tri-fold menu card',
  },
  {
    id: 'menu-cocktail',
    name: 'Cocktail Menu',
    category: 'Menus',
    width: 1200,
    height: 3300,
    icon: '🍸',
    description: 'Narrow bar / cocktail menu',
  },
  {
    id: 'menu-dessert',
    name: 'Dessert Menu',
    category: 'Menus',
    width: 1500,
    height: 2100,
    icon: '🍰',
    description: '5" × 7" dessert menu card',
  },
  {
    id: 'menu-kids',
    name: "Kids' Menu",
    category: 'Menus',
    width: 2550,
    height: 3300,
    icon: '🧒',
    description: "Children's activity menu",
  },
  {
    id: 'menu-table-tent',
    name: 'Table Tent Menu',
    category: 'Menus',
    width: 1200,
    height: 1800,
    icon: '🔺',
    description: 'Table tent menu display',
  },
  {
    id: 'menu-cafe',
    name: 'Café / Coffee Menu',
    category: 'Menus',
    width: 1800,
    height: 2400,
    icon: '☕',
    description: 'Coffee shop menu board',
  },
  {
    id: 'menu-takeout',
    name: 'Takeout Menu',
    category: 'Menus',
    width: 2550,
    height: 3300,
    icon: '📦',
    description: 'Delivery / takeout menu',
  },
  {
    id: 'menu-wine',
    name: 'Wine List',
    category: 'Menus',
    width: 1500,
    height: 3300,
    icon: '🍷',
    description: 'Wine list / beverage menu',
  },

  // ─────────────────────────────────────────────────────────
  // RESUMES & CVs (10 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'resume-us-letter',
    name: 'Resume (US Letter)',
    category: 'Resumes',
    width: 2550,
    height: 3300,
    icon: '📝',
    description: 'Standard resume at 300 DPI',
  },
  {
    id: 'resume-a4',
    name: 'Resume (A4)',
    category: 'Resumes',
    width: 2480,
    height: 3508,
    icon: '📝',
    description: 'A4 curriculum vitae',
  },
  {
    id: 'resume-creative',
    name: 'Creative Resume',
    category: 'Resumes',
    width: 2550,
    height: 3300,
    icon: '🎨',
    description: 'Visual / creative CV layout',
  },
  {
    id: 'resume-minimal',
    name: 'Minimal Resume',
    category: 'Resumes',
    width: 2550,
    height: 3300,
    icon: '✨',
    description: 'Clean minimal CV',
  },
  {
    id: 'resume-two-column',
    name: 'Two-Column Resume',
    category: 'Resumes',
    width: 2550,
    height: 3300,
    icon: '📋',
    description: 'Sidebar + main content layout',
  },
  {
    id: 'resume-infographic',
    name: 'Infographic Resume',
    category: 'Resumes',
    width: 2550,
    height: 3300,
    icon: '📊',
    description: 'Data-driven visual resume',
  },
  {
    id: 'cover-letter',
    name: 'Cover Letter',
    category: 'Resumes',
    width: 2550,
    height: 3300,
    icon: '✉️',
    description: 'Matching cover letter page',
  },
  {
    id: 'portfolio-page',
    name: 'Portfolio Page',
    category: 'Resumes',
    width: 1920,
    height: 1080,
    icon: '🖼️',
    description: 'Portfolio showcase slide',
  },
  {
    id: 'linkedin-portfolio-banner',
    name: 'LinkedIn Portfolio Banner',
    category: 'Resumes',
    width: 1584,
    height: 396,
    icon: '💼',
    description: 'LinkedIn featured section banner',
  },
  {
    id: 'reference-letter',
    name: 'Reference Letter',
    category: 'Resumes',
    width: 2550,
    height: 3300,
    icon: '📄',
    description: 'Professional reference letter',
  },

  // ─────────────────────────────────────────────────────────
  // INFOGRAPHICS (10 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'infographic-standard',
    name: 'Infographic (Standard)',
    category: 'Infographics',
    width: 2400,
    height: 6000,
    icon: '📊',
    description: '800×2000px base at 3x',
  },
  {
    id: 'infographic-timeline',
    name: 'Timeline Infographic',
    category: 'Infographics',
    width: 2400,
    height: 7200,
    icon: '📅',
    description: 'Vertical timeline layout',
  },
  {
    id: 'infographic-comparison',
    name: 'Comparison Infographic',
    category: 'Infographics',
    width: 2400,
    height: 4800,
    icon: '⚖️',
    description: 'Side-by-side comparison',
  },
  {
    id: 'infographic-process',
    name: 'Process / Steps',
    category: 'Infographics',
    width: 2400,
    height: 5400,
    icon: '🔄',
    description: 'Step-by-step process flow',
  },
  {
    id: 'infographic-stats',
    name: 'Statistics Infographic',
    category: 'Infographics',
    width: 2400,
    height: 4200,
    icon: '📈',
    description: 'Data and stats showcase',
  },
  {
    id: 'infographic-list',
    name: 'List Infographic',
    category: 'Infographics',
    width: 2400,
    height: 5400,
    icon: '📋',
    description: 'Top 10 / numbered list',
  },
  {
    id: 'infographic-map',
    name: 'Map Infographic',
    category: 'Infographics',
    width: 3600,
    height: 2400,
    icon: '🗺️',
    description: 'Geographic data visualization',
  },
  {
    id: 'infographic-report',
    name: 'Annual Report Page',
    category: 'Infographics',
    width: 2480,
    height: 3508,
    icon: '📑',
    description: 'Report data page',
  },
  {
    id: 'infographic-social',
    name: 'Social Media Infographic',
    category: 'Infographics',
    width: 1080,
    height: 1920,
    icon: '📊',
    description: 'Instagram-ready infographic',
  },
  {
    id: 'infographic-wide',
    name: 'Wide Infographic',
    category: 'Infographics',
    width: 4800,
    height: 2400,
    icon: '📊',
    description: 'Horizontal data spread',
  },

  // ─────────────────────────────────────────────────────────
  // CERTIFICATES & AWARDS (10 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'certificate-landscape',
    name: 'Certificate (Landscape)',
    category: 'Certificates',
    width: 3300,
    height: 2550,
    icon: '🏆',
    description: 'Standard certificate',
  },
  {
    id: 'certificate-portrait',
    name: 'Certificate (Portrait)',
    category: 'Certificates',
    width: 2550,
    height: 3300,
    icon: '🏆',
    description: 'Vertical certificate',
  },
  {
    id: 'certificate-a4-landscape',
    name: 'Certificate A4',
    category: 'Certificates',
    width: 3508,
    height: 2480,
    icon: '🏆',
    description: 'A4 landscape certificate',
  },
  {
    id: 'diploma',
    name: 'Diploma',
    category: 'Certificates',
    width: 3300,
    height: 2550,
    icon: '🎓',
    description: 'Graduation diploma',
  },
  {
    id: 'achievement-award',
    name: 'Achievement Award',
    category: 'Certificates',
    width: 3300,
    height: 2550,
    icon: '⭐',
    description: 'Employee / student award',
  },
  {
    id: 'training-certificate',
    name: 'Training Certificate',
    category: 'Certificates',
    width: 3300,
    height: 2550,
    icon: '📋',
    description: 'Course completion certificate',
  },
  {
    id: 'appreciation-award',
    name: 'Appreciation Award',
    category: 'Certificates',
    width: 3300,
    height: 2550,
    icon: '🙏',
    description: 'Certificate of appreciation',
  },
  {
    id: 'participation-cert',
    name: 'Participation Certificate',
    category: 'Certificates',
    width: 3300,
    height: 2550,
    icon: '🎖️',
    description: 'Event participation certificate',
  },
  {
    id: 'volunteer-cert',
    name: 'Volunteer Certificate',
    category: 'Certificates',
    width: 3300,
    height: 2550,
    icon: '🤝',
    description: 'Volunteer appreciation',
  },
  {
    id: 'membership-card',
    name: 'Membership Card',
    category: 'Certificates',
    width: 1050,
    height: 600,
    icon: '🪪',
    description: 'Organization membership card',
  },

  // ─────────────────────────────────────────────────────────
  // ADS & BANNERS (15 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'ad-facebook-square',
    name: 'Facebook Ad (Square)',
    category: 'Ads & Banners',
    width: 1080,
    height: 1080,
    icon: '📢',
    description: 'Square Facebook ad',
  },
  {
    id: 'ad-facebook-story',
    name: 'Facebook Story Ad',
    category: 'Ads & Banners',
    width: 1080,
    height: 1920,
    icon: '📢',
    description: 'Full-screen story ad',
  },
  {
    id: 'ad-instagram-square',
    name: 'Instagram Ad (Square)',
    category: 'Ads & Banners',
    width: 1080,
    height: 1080,
    icon: '📢',
    description: 'Square Instagram ad',
  },
  {
    id: 'ad-instagram-story',
    name: 'Instagram Story Ad',
    category: 'Ads & Banners',
    width: 1080,
    height: 1920,
    icon: '📢',
    description: 'Full-screen story ad',
  },
  {
    id: 'ad-google-responsive',
    name: 'Google Responsive Ad',
    category: 'Ads & Banners',
    width: 1200,
    height: 628,
    icon: '📢',
    description: 'Google responsive display ad',
  },
  {
    id: 'ad-banner-468x60',
    name: 'Banner (468×60)',
    category: 'Ads & Banners',
    width: 468,
    height: 60,
    icon: '🌐',
    description: 'Full banner IAB',
  },
  {
    id: 'ad-banner-320x50',
    name: 'Mobile Banner',
    category: 'Ads & Banners',
    width: 320,
    height: 50,
    icon: '📱',
    description: 'Mobile leaderboard ad',
  },
  {
    id: 'ad-banner-320x100',
    name: 'Mobile Large Banner',
    category: 'Ads & Banners',
    width: 320,
    height: 100,
    icon: '📱',
    description: 'Large mobile banner',
  },
  {
    id: 'ad-half-page',
    name: 'Half-Page Ad',
    category: 'Ads & Banners',
    width: 300,
    height: 600,
    icon: '🌐',
    description: 'Half-page ad unit',
  },
  {
    id: 'ad-interstitial',
    name: 'Interstitial Ad',
    category: 'Ads & Banners',
    width: 1024,
    height: 768,
    icon: '📱',
    description: 'Full-screen interstitial',
  },
  {
    id: 'ad-native',
    name: 'Native Ad Card',
    category: 'Ads & Banners',
    width: 1200,
    height: 627,
    icon: '📰',
    description: 'In-feed native ad',
  },
  {
    id: 'ad-sponsored-post',
    name: 'Sponsored Content',
    category: 'Ads & Banners',
    width: 1200,
    height: 630,
    icon: '📰',
    description: 'Sponsored content image',
  },
  {
    id: 'ad-amazon-product',
    name: 'Amazon Product Image',
    category: 'Ads & Banners',
    width: 2000,
    height: 2000,
    icon: '📦',
    description: 'Amazon product listing photo',
  },
  {
    id: 'ad-shopify-product',
    name: 'Shopify Product Image',
    category: 'Ads & Banners',
    width: 2048,
    height: 2048,
    icon: '🛒',
    description: 'E-commerce product photo',
  },
  {
    id: 'ad-etsy-listing',
    name: 'Etsy Listing Image',
    category: 'Ads & Banners',
    width: 2000,
    height: 2000,
    icon: '🧶',
    description: 'Etsy product listing photo',
  },

  // ─────────────────────────────────────────────────────────
  // EDUCATION (12 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'worksheet-letter',
    name: 'Worksheet',
    category: 'Education',
    width: 2550,
    height: 3300,
    icon: '📝',
    description: 'US Letter worksheet',
  },
  {
    id: 'lesson-plan',
    name: 'Lesson Plan',
    category: 'Education',
    width: 2550,
    height: 3300,
    icon: '📚',
    description: 'Teacher lesson plan page',
  },
  {
    id: 'class-schedule',
    name: 'Class Schedule',
    category: 'Education',
    width: 2550,
    height: 3300,
    icon: '🗓️',
    description: 'Weekly class schedule',
  },
  {
    id: 'report-card',
    name: 'Report Card',
    category: 'Education',
    width: 2550,
    height: 3300,
    icon: '📋',
    description: 'Student report card',
  },
  {
    id: 'book-cover-6x9',
    name: 'Book Cover (6×9)',
    category: 'Education',
    width: 1800,
    height: 2700,
    icon: '📖',
    description: 'Standard book cover',
  },
  {
    id: 'book-cover-5x8',
    name: 'Book Cover (5×8)',
    category: 'Education',
    width: 1500,
    height: 2400,
    icon: '📖',
    description: 'Pocket / trade paperback',
  },
  {
    id: 'reading-log',
    name: 'Reading Log',
    category: 'Education',
    width: 2550,
    height: 3300,
    icon: '📚',
    description: 'Student reading tracker',
  },
  {
    id: 'science-poster',
    name: 'Science Fair Poster',
    category: 'Education',
    width: 10800,
    height: 4320,
    icon: '🔬',
    description: '36" × 48" tri-panel poster',
  },
  {
    id: 'study-guide',
    name: 'Study Guide',
    category: 'Education',
    width: 2550,
    height: 3300,
    icon: '🎓',
    description: 'Study material cheat sheet',
  },
  {
    id: 'mindmap',
    name: 'Mind Map',
    category: 'Education',
    width: 3000,
    height: 2000,
    icon: '🧠',
    description: 'Concept / mind map canvas',
  },
  {
    id: 'storyboard',
    name: 'Storyboard',
    category: 'Education',
    width: 3300,
    height: 2550,
    icon: '🎬',
    description: 'Film / animation storyboard',
  },
  {
    id: 'comic-strip',
    name: 'Comic Strip',
    category: 'Education',
    width: 3000,
    height: 1000,
    icon: '💬',
    description: 'Horizontal comic strip',
  },

  // ─────────────────────────────────────────────────────────
  // MISCELLANEOUS (12 templates)
  // ─────────────────────────────────────────────────────────
  {
    id: 'album-cover',
    name: 'Album Cover',
    category: 'Misc',
    width: 3000,
    height: 3000,
    icon: '🎵',
    description: 'Music album cover art',
  },
  {
    id: 'desktop-wallpaper',
    name: 'Desktop Wallpaper',
    category: 'Misc',
    width: 2560,
    height: 1440,
    icon: '🖥️',
    description: '2K desktop wallpaper',
  },
  {
    id: 'phone-wallpaper',
    name: 'Phone Wallpaper',
    category: 'Misc',
    width: 1170,
    height: 2532,
    icon: '📱',
    description: 'iPhone 14 wallpaper size',
  },
  {
    id: 'ipad-wallpaper',
    name: 'iPad Wallpaper',
    category: 'Misc',
    width: 2048,
    height: 2732,
    icon: '📱',
    description: 'iPad Pro wallpaper',
  },
  {
    id: 'coloring-page',
    name: 'Coloring Page',
    category: 'Misc',
    width: 2550,
    height: 3300,
    icon: '🖍️',
    description: 'Printable coloring page',
  },
  {
    id: 'vision-board',
    name: 'Vision Board',
    category: 'Misc',
    width: 3000,
    height: 2000,
    icon: '🌟',
    description: 'Goals / vision board collage',
  },
  {
    id: 'mood-board',
    name: 'Mood Board',
    category: 'Misc',
    width: 2000,
    height: 2000,
    icon: '🎨',
    description: 'Creative inspiration board',
  },
  {
    id: 'scrapbook-page',
    name: 'Scrapbook Page',
    category: 'Misc',
    width: 3600,
    height: 3600,
    icon: '📸',
    description: '12" × 12" scrapbook page',
  },
  {
    id: 'calendar-monthly',
    name: 'Monthly Calendar',
    category: 'Misc',
    width: 3300,
    height: 2550,
    icon: '📅',
    description: 'Printable monthly calendar',
  },
  {
    id: 'planner-page',
    name: 'Daily Planner Page',
    category: 'Misc',
    width: 2550,
    height: 3300,
    icon: '📆',
    description: 'Daily planner / organizer',
  },
  {
    id: 'photo-collage-square',
    name: 'Photo Collage (Square)',
    category: 'Misc',
    width: 2000,
    height: 2000,
    icon: '📷',
    description: 'Square photo collage',
  },
  {
    id: 'photo-collage-landscape',
    name: 'Photo Collage (Wide)',
    category: 'Misc',
    width: 3000,
    height: 2000,
    icon: '📷',
    description: 'Landscape photo collage',
  },

  // ─────────────────────────────────────────────────────────
  // CUSTOM (always last)
  // ─────────────────────────────────────────────────────────
  {
    id: 'custom',
    name: 'Custom Size',
    category: 'Custom',
    width: 1080,
    height: 1080,
    icon: '✏️',
    description: 'Enter your own dimensions',
  },
];

export const TEMPLATE_CATEGORIES = [
  'All',
  ...Array.from(new Set(DESIGN_TEMPLATES.map((t) => t.category))),
];
