// SPDX-License-Identifier: Apache-2.0
import { describe, expect, it } from 'vitest';
import {
  buildAnalysisReport,
  extractIconLinksFromHtml,
  normalizeWebsiteUrl,
} from '@/lib/favicon-analysis';
import {
  createFrameworkSnippets,
  createWebManifest,
  sanitizeSvgMarkup,
} from '@/lib/favicon-studio';

describe('favicon tool helpers', () => {
  it('normalizes bare domains to https URLs', () => {
    expect(normalizeWebsiteUrl('example.com')).toBe('https://example.com/');
  });

  it('extracts and resolves icon links from HTML markup', () => {
    const html = `
      <html>
        <head>
          <link rel="icon" href="/favicon-32x32.png" sizes="32x32" type="image/png">
          <link rel="apple-touch-icon" href="https://cdn.example.com/apple-touch-icon.png" sizes="180x180">
        </head>
      </html>
    `;

    const links = extractIconLinksFromHtml(html, 'https://example.com/docs');

    expect(links).toHaveLength(2);
    expect(links[0]).toMatchObject({
      url: 'https://example.com/favicon-32x32.png',
      sizes: '32x32',
      source: 'markup',
    });
    expect(links[1]).toMatchObject({
      url: 'https://cdn.example.com/apple-touch-icon.png',
      rel: 'apple-touch-icon',
      source: 'markup',
    });
  });

  it('builds a web manifest with maskable icons', () => {
    const manifest = createWebManifest({
      appName: 'ImageMan',
      shortName: 'IM',
      themeColor: '#123456',
      backgroundColor: '#ffffff',
    });

    expect(manifest.name).toBe('ImageMan');
    expect(manifest.short_name).toBe('IM');
    expect(manifest.icons).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ src: '/android-chrome-192x192.png', purpose: 'any' }),
        expect.objectContaining({ src: '/android-chrome-maskable-512x512.png', purpose: 'maskable' }),
      ]),
    );
  });

  it('creates framework snippets that reference the generated manifest', () => {
    const snippets = createFrameworkSnippets({
      appName: 'ImageMan',
      themeColor: '#123456',
      backgroundColor: '#ffffff',
    });

    expect(snippets.html5).toContain('/site.webmanifest');
    expect(snippets.nextjs).toContain("url: '/favicon.ico'");
    expect(snippets.react).toContain('react-helmet');
  });

  it('strips common SVG export noise', () => {
    const dirtySvg = `
      <?xml version="1.0" encoding="UTF-8"?>
      <!-- exported -->
      <svg xmlns="http://www.w3.org/2000/svg">
        <metadata>generated by tool</metadata>
        <rect width="10" height="10" />
      </svg>
    `;

    const cleanedSvg = sanitizeSvgMarkup(dirtySvg);

    expect(cleanedSvg).toContain('<svg');
    expect(cleanedSvg).toContain('<rect width="10" height="10" />');
    expect(cleanedSvg).not.toContain('<?xml');
    expect(cleanedSvg).not.toContain('<metadata>');
    expect(cleanedSvg).not.toContain('<!--');
  });

  it('formats analysis results into a readable text report', () => {
    const report = buildAnalysisReport({
      url: 'https://example.com',
      timestamp: '2026-01-01T00:00:00.000Z',
      files: [
        {
          url: 'https://example.com/favicon.ico',
          type: 'ico',
          exists: true,
          fileSize: 4096,
          loadTime: 120,
        },
      ],
      performance: {
        totalLoadTime: 120,
        totalFileSize: 4096,
        averageLoadTime: 120,
        largestFile: { url: 'https://example.com/favicon.ico', size: 4096 },
        slowestFile: { url: 'https://example.com/favicon.ico', time: 120 },
      },
      compatibility: [
        { browser: 'Chrome', supported: true, icon: 'C', notes: 'Full support' },
      ],
      bestPractices: [
        {
          id: 'has-ico',
          title: 'favicon.ico exists',
          description: 'Legacy support',
          status: 'pass',
        },
      ],
      score: 100,
      grade: 'A',
    });

    expect(report).toContain('Favicon Analysis Report');
    expect(report).toContain('Score: 100/100 (A)');
    expect(report).toContain('https://example.com/favicon.ico');
  });
});