// SPDX-License-Identifier: Apache-2.0
import { constants } from 'node:fs';
import { access, writeFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { resolve } from 'node:path';

const args = process.argv.slice(2);
const shouldPrintToStdout = args.includes('--stdout');
const shouldForce = args.includes('--force');
const fileFlagIndex = args.findIndex((arg) => arg === '--file');

if (fileFlagIndex >= 0 && !args[fileFlagIndex + 1]) {
 throw new Error('Expected a file path after --file');
}

const outputFile = fileFlagIndex >= 0 ? args[fileFlagIndex + 1] : '.env.self-host';

function generateSecret() {
 return randomBytes(32).toString('hex');
}

function buildEnvFile() {
 return [
  '# img-man self-host bootstrap',
  '# Generated by scripts/self-host-bootstrap.ts',
    'IMAGEMAN_PORT=3000',
  'PORT=3000',
  'NEXTAUTH_URL=http://localhost:3000',
  `NEXTAUTH_SECRET=${generateSecret()}`,
  `ASSET_URL_SIGNING_SECRET=${generateSecret()}`,
  'AUTH_TRUST_HOST=true',
    'MONGODB_URI=mongodb://mongo:27017/imageman',
  'MONGODB_DB=imageman',
  '',
    '# If you run img-man outside Docker Compose, change MONGODB_URI to',
    '# mongodb://localhost:27017/imageman or your Atlas connection string.',
    '',
  '# Optional OAuth providers',
  '# GOOGLE_CLIENT_ID=',
  '# GOOGLE_CLIENT_SECRET=',
  '# GITHUB_CLIENT_ID=',
  '# GITHUB_CLIENT_SECRET=',
  '',
  '# Optional storage defaults for upload/download flows',
  '# Required if you want self-hosted asset uploads without first connecting BYOC in the dashboard.',
  '# GCP_PROJECT_ID=',
  '# GCP_STORAGE_BUCKET=',
  '# GCP_APP_CREDENTIALS_PATH=',
  '',
 ].join('\n');
}

async function ensureOutputDoesNotExist(outputPath: string) {
 try {
  await access(outputPath, constants.F_OK);
 } catch {
  return;
 }

 if (!shouldForce) {
  throw new Error(
   `${outputPath} already exists. Re-run with --force or choose --file <path>.`,
  );
 }
}

async function main() {
 const content = buildEnvFile();

 if (shouldPrintToStdout) {
  process.stdout.write(`${content}\n`);
  return;
 }

 const outputPath = resolve(process.cwd(), outputFile);
 await ensureOutputDoesNotExist(outputPath);
 await writeFile(outputPath, `${content}\n`, 'utf8');
 console.log(`Wrote ${outputPath}`);
}

main().catch((error) => {
 console.error(error instanceof Error ? error.message : error);
 process.exitCode = 1;
});